### ISSUE TITLE
As a user, I want to load a page for a specific goal so that I can view information and data on that goal.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#1]
Description: In this project, we have 17 goals which mean we would have 17 pages. Each page will be presenting data for a specific goal.

Acceptance Criteria:
- [x] This is just having a blank page for each goal with the appropriate background colour.

**Comment by partini** [comment]
@dafinaolluri please add description and acceptance criteria.
