### ISSUE TITLE
As a user I want to have 17 SDG Icons so I can easily navigate to specific goals by clicking on an icon.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/unkt-sdg-plugin#10]
Description:
Each clicked icon brings us to an empty SDG Goal page.

Acceptance Criteria:
- [x] Each clicked icon brings us to an empty SDG Goal page.

**Comment by georgeslabreche** [comment]
@dafinaolluri @partini @artaabdullahu this is not accepted because 1) the issue isn't associated with a milestone and 2) nobody is assigned to it.
