### ISSUE TITLE
As a developer I want to implement the landing page design as per requirements.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/unkt-sdg-plugin#11]
Description:
Landing page of the plugin should be designed as per designs sent by Ozren, attached with this task.

Acceptance Criteria:
- [x] There is an SDG Icon in the header of the page.
- [x] We have a short description of SDG's
- [x] h1 title is hidden but should be there because of google: "Sustainable Development Goals"
- [x] Over it there should be this image from UN page as a header 
- [x] Body text is same as the rest of the site (Roboto 18pt)
- [x] SDGs go by 3 in the grid with 20px gutter between them
- [x] Icons are presented as IMG's wraped by empty href tags.

![v2](https://cloud.githubusercontent.com/assets/7932995/21849761/b01b7b82-d807-11e6-99a1-40c18f1f3453.jpg)

**Comment by georgeslabreche** [comment]
@dafinaolluri @partini please make sure we have acceptance criteria to check that this is implemented in a responsive and mobile friendly manner. If using bootstrap, this means using a responsive 3x6 grid like so: http://bit.ly/2j1zEgl

**Comment by artaabdullahu** [comment]
@partini I don't have the link who I can test this task. Please can you tell me...

**Comment by artaabdullahu** [comment]
I can not accepted this task. Well, this is what I can see without a header and some point that are wrote in Acceptance Criteria:
<img width="1280" alt="screen shot 2017-03-02 at 11 27 55 am" src="https://cloud.githubusercontent.com/assets/21961919/23503311/7ad84c2e-ff3b-11e6-831c-261d476eb721.png">
