### ISSUE TITLE
As an Administrator I want to have the possibility for Adding Indicators, so I can save and add indicators in the database.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/unkt-sdg-plugin#16]
Description: 
When we go to SDGs & Indicators admin page, we should have the possibility to add new indicators.

Acceptance Criteria:

- [x] When we click +Add Indicator we are shown a modal with 3 fields: Indicator Name[textfield], SDG[dropdown field], Description[textarea] 

- [x] Clicking Save indicator on modal saves the indicator in the database and lists it in the indicators table.

**Comment by artaabdullahu** [comment]
@partini This task is working good according to the requirements but have problem with ID of indicators. When I add indicators the ID is not shows expect If i do reload page.
