### ISSUE TITLE
As an Administrator I want to have Indicator measurements preview chart, so I can preview the chart based on data that I put.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/unkt-sdg-plugin#18]

**Comment by partini** [comment]
@georgeslabreche @ferideadili @dafinaolluri I think there is no need for a preview chart functionality since we are publishing everything right away, I've added a link to the page on the top of the table so you can immediately go to the front-end page and see the results.

**Comment by georgeslabreche** [comment]
@partini let's just put this back in New Issue. I think what we need instead is a way to individually published/unpublish each chart we create. Would just be a boolean flag indicating if we should render the chart or not. @dafinaolluri can you create a New Issue for this?
