### ISSUE TITLE
As a user, I want information on the page to tell me which goal page I am viewing so that I can be aware of what I am looking at.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#2]
"As a user, I want information on the page to tell me which goal page I am viewing so that I can be aware of what I am looking at" 

Acceptance Criteria: 
- [x]  The SDG square image logo needs to display on the upper left-hand corner, as per design
- [x] The page has a title.
- [x] The page has a description.
- [x]  Loading a different SDG page updates the square image logo, the title, then description, and the background color.

**Comment by partini** [comment]
@dafinaolluri please consult @artaabdullahu on how to turn these Acceptance Criteria items into checkboxes.

**Comment by dafinaolluri** [comment]
@partini Already did 👍
