### ISSUE TITLE
As an administrator, I want to have the Delete Indicator so i can delete the indicator from the database.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#28]
Description:
When we click the delete icon on indicators list the corresponding indicator is removed from the database and from the indicators table.

Acceptance Criteria:

- [x]  When we click the delete icon on indicators list the corresponding indicator is removed from the database and from the indicators table.

**Comment by artaabdullahu** [comment]
@partini **Delete button** is  not working in second page of SDG Indicators.
