### ISSUE TITLE
Update Read Me File

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#31]

**Comment by georgeslabreche** [comment]
@dafinaolluri @partini update how? Please be more specific.

README should be updated as a best practice habit when we work on issues and implement new feature rather than having a specific README update issue every time. This is like having an issue for "commit the code".

**Comment by partini** [comment]
@georgeslabreche We need to compile a readme file similar to this one: https://wordpress.org/plugins/about/readme.txt . That's why we have this task.
