### ISSUE TITLE
Improve browser caching of UNKT site

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/unkt-sdg-plugin#34]
<img width="959" alt="screen shot 2017-01-31 at 2 44 14 pm" src="https://cloud.githubusercontent.com/assets/1258236/22467215/04eaebf4-e7c4-11e6-8967-af90f7057e33.png">

The solution isn't as simple as installing a plugin like or [W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) or [WP Super Cache](https://wordpress.org/plugins/wp-super-cache/) because it could interfere with rocket cache which is what we are using for caching.

**Comment by partini** [comment]
@dafinaolluri @georgeslabreche Closing this issue because is not related to the plugin, and the task is finished.
