### ISSUE TITLE
Cut description text on datatable, its not looking good when the text is long

### ISSUE THREAD

**Issue by ferideadili** [opendatakosovo/unkt-sdg-plugin#43]

**Comment by partini** [comment]
@dafinaolluri Should we put a text limit on the descriptions?

**Comment by partini** [comment]
@dafinaolluri see screenshot where the description of the indicator is.
![screen shot 2017-03-21 at 10 38 09 am](https://cloud.githubusercontent.com/assets/7932995/24141079/92327926-0e22-11e7-8a45-181c0ee2a947.png)

**Comment by partini** [comment]
@dafinaolluri This is where the description is presented in front-end.
![screen shot 2017-03-21 at 10 39 25 am](https://cloud.githubusercontent.com/assets/7932995/24141114/b61a1970-0e22-11e7-8018-ec55113d42fc.png)

**Comment by dafinaolluri** [comment]
@partini For now, we don't need to put a limit on the description.

**Comment by dafinaolluri** [comment]
@artaabdullahu @partini We tested with Arta, it's looking good for now. I will leave in the Done Column in case after the meeting tomorrow they want to put a limit to it.
