### ISSUE TITLE
The unit should be included with the number when you hover on one of the points.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#49]

**Comment by artaabdullahu** [comment]
Based on functionality is OK. But field who displayed date, value and unit when you hover on  one of the point it is not responsive. SO, just unit is not fulland please see on the screenshot.
![screenshot from 2017-03-22 17 29 23](https://cloud.githubusercontent.com/assets/21961919/24209098/96624482-0f25-11e7-8a31-7f076df612c2.png)
