### ISSUE TITLE
Change in measurement order of the columns: Interchange Source and Notes

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/unkt-sdg-plugin#52]

**Comment by artaabdullahu** [comment]
Maybe is not working well at me, but it still same problem:
 
![screenshot from 2017-03-22 17 39 56](https://cloud.githubusercontent.com/assets/21961919/24209503/cae41e00-0f26-11e7-807e-b0a04d58db39.png)

**Comment by artaabdullahu** [comment]
@dafinaolluri Please put on Sprint this task. I think this task is created for this week and it is completed also. Thanks :)
